#ifndef F_KEY_FUNC_H
#define F_KEY_FUNC_H

#define F_KEY_FUNC(key)       \
	void _f##key() {          \
        cursorFind(key);      \
	}

#define DEF_F_KEY_FUNCS \
	F_KEY_FUNC(33)      \
	F_KEY_FUNC(34)      \
	F_KEY_FUNC(35)      \
	F_KEY_FUNC(36)      \
	F_KEY_FUNC(37)      \
	F_KEY_FUNC(38)      \
	F_KEY_FUNC(39)      \
	F_KEY_FUNC(40)      \
	F_KEY_FUNC(41)      \
	F_KEY_FUNC(42)      \
	F_KEY_FUNC(43)      \
	F_KEY_FUNC(44)      \
	F_KEY_FUNC(45)      \
	F_KEY_FUNC(46)      \
	F_KEY_FUNC(47)      \
	F_KEY_FUNC(48)      \
	F_KEY_FUNC(49)      \
	F_KEY_FUNC(50)      \
	F_KEY_FUNC(51)      \
	F_KEY_FUNC(52)      \
	F_KEY_FUNC(53)      \
	F_KEY_FUNC(54)      \
	F_KEY_FUNC(55)      \
	F_KEY_FUNC(56)      \
	F_KEY_FUNC(57)      \
	F_KEY_FUNC(58)      \
	F_KEY_FUNC(59)      \
	F_KEY_FUNC(60)      \
	F_KEY_FUNC(61)      \
	F_KEY_FUNC(62)      \
	F_KEY_FUNC(63)      \
	F_KEY_FUNC(64)      \
	F_KEY_FUNC(65)      \
	F_KEY_FUNC(66)      \
	F_KEY_FUNC(67)      \
	F_KEY_FUNC(68)      \
	F_KEY_FUNC(69)      \
	F_KEY_FUNC(70)      \
	F_KEY_FUNC(71)      \
	F_KEY_FUNC(72)      \
	F_KEY_FUNC(73)      \
	F_KEY_FUNC(74)      \
	F_KEY_FUNC(75)      \
	F_KEY_FUNC(76)      \
	F_KEY_FUNC(77)      \
	F_KEY_FUNC(78)      \
	F_KEY_FUNC(79)      \
	F_KEY_FUNC(80)      \
	F_KEY_FUNC(81)      \
	F_KEY_FUNC(82)      \
	F_KEY_FUNC(83)      \
	F_KEY_FUNC(84)      \
	F_KEY_FUNC(85)      \
	F_KEY_FUNC(86)      \
	F_KEY_FUNC(87)      \
	F_KEY_FUNC(88)      \
	F_KEY_FUNC(89)      \
	F_KEY_FUNC(90)      \
	F_KEY_FUNC(91)      \
	F_KEY_FUNC(92)      \
	F_KEY_FUNC(93)      \
	F_KEY_FUNC(94)      \
	F_KEY_FUNC(95)      \
	F_KEY_FUNC(96)      \
	F_KEY_FUNC(97)      \
	F_KEY_FUNC(98)      \
	F_KEY_FUNC(99)      \
	F_KEY_FUNC(100)     \
	F_KEY_FUNC(101)     \
	F_KEY_FUNC(102)     \
	F_KEY_FUNC(103)     \
	F_KEY_FUNC(104)     \
	F_KEY_FUNC(105)     \
	F_KEY_FUNC(106)     \
	F_KEY_FUNC(107)     \
	F_KEY_FUNC(108)     \
	F_KEY_FUNC(109)     \
	F_KEY_FUNC(110)     \
	F_KEY_FUNC(111)     \
	F_KEY_FUNC(112)     \
	F_KEY_FUNC(113)     \
	F_KEY_FUNC(114)     \
	F_KEY_FUNC(115)     \
	F_KEY_FUNC(116)     \
	F_KEY_FUNC(117)     \
	F_KEY_FUNC(118)     \
	F_KEY_FUNC(119)     \
	F_KEY_FUNC(120)     \
	F_KEY_FUNC(121)     \
	F_KEY_FUNC(122)     \
	F_KEY_FUNC(123)     \
	F_KEY_FUNC(124)     \
	F_KEY_FUNC(125)     \
	F_KEY_FUNC(126)

#define F_KEY_REGISTER(key)                                                                                   \
	{                                                                                                         \
		char str[16];                                                                                         \
		sprintf(str, "f%c", key);                                                                             \
		KeyChain chain = str2KeyChain(str);                                                                   \
		registerKeyBinding(chain, _f##key, MODE_NORMAL | MODE_VISUAL | MODE_VISUAL_BLOCK | MODE_VISUAL_LINE); \
	}

#define F_KEY_FUNC_REGISTER \
	F_KEY_REGISTER(33)      \
	F_KEY_REGISTER(34)      \
	F_KEY_REGISTER(35)      \
	F_KEY_REGISTER(36)      \
	F_KEY_REGISTER(37)      \
	F_KEY_REGISTER(38)      \
	F_KEY_REGISTER(39)      \
	F_KEY_REGISTER(40)      \
	F_KEY_REGISTER(41)      \
	F_KEY_REGISTER(42)      \
	F_KEY_REGISTER(43)      \
	F_KEY_REGISTER(44)      \
	F_KEY_REGISTER(45)      \
	F_KEY_REGISTER(46)      \
	F_KEY_REGISTER(47)      \
	F_KEY_REGISTER(48)      \
	F_KEY_REGISTER(49)      \
	F_KEY_REGISTER(50)      \
	F_KEY_REGISTER(51)      \
	F_KEY_REGISTER(52)      \
	F_KEY_REGISTER(53)      \
	F_KEY_REGISTER(54)      \
	F_KEY_REGISTER(55)      \
	F_KEY_REGISTER(56)      \
	F_KEY_REGISTER(57)      \
	F_KEY_REGISTER(58)      \
	F_KEY_REGISTER(59)      \
	F_KEY_REGISTER(60)      \
	F_KEY_REGISTER(61)      \
	F_KEY_REGISTER(62)      \
	F_KEY_REGISTER(63)      \
	F_KEY_REGISTER(64)      \
	F_KEY_REGISTER(65)      \
	F_KEY_REGISTER(66)      \
	F_KEY_REGISTER(67)      \
	F_KEY_REGISTER(68)      \
	F_KEY_REGISTER(69)      \
	F_KEY_REGISTER(70)      \
	F_KEY_REGISTER(71)      \
	F_KEY_REGISTER(72)      \
	F_KEY_REGISTER(73)      \
	F_KEY_REGISTER(74)      \
	F_KEY_REGISTER(75)      \
	F_KEY_REGISTER(76)      \
	F_KEY_REGISTER(77)      \
	F_KEY_REGISTER(78)      \
	F_KEY_REGISTER(79)      \
	F_KEY_REGISTER(80)      \
	F_KEY_REGISTER(81)      \
	F_KEY_REGISTER(82)      \
	F_KEY_REGISTER(83)      \
	F_KEY_REGISTER(84)      \
	F_KEY_REGISTER(85)      \
	F_KEY_REGISTER(86)      \
	F_KEY_REGISTER(87)      \
	F_KEY_REGISTER(88)      \
	F_KEY_REGISTER(89)      \
	F_KEY_REGISTER(90)      \
	F_KEY_REGISTER(91)      \
	F_KEY_REGISTER(92)      \
	F_KEY_REGISTER(93)      \
	F_KEY_REGISTER(94)      \
	F_KEY_REGISTER(95)      \
	F_KEY_REGISTER(96)      \
	F_KEY_REGISTER(97)      \
	F_KEY_REGISTER(98)      \
	F_KEY_REGISTER(99)      \
	F_KEY_REGISTER(100)     \
	F_KEY_REGISTER(101)     \
	F_KEY_REGISTER(102)     \
	F_KEY_REGISTER(103)     \
	F_KEY_REGISTER(104)     \
	F_KEY_REGISTER(105)     \
	F_KEY_REGISTER(106)     \
	F_KEY_REGISTER(107)     \
	F_KEY_REGISTER(108)     \
	F_KEY_REGISTER(109)     \
	F_KEY_REGISTER(110)     \
	F_KEY_REGISTER(111)     \
	F_KEY_REGISTER(112)     \
	F_KEY_REGISTER(113)     \
	F_KEY_REGISTER(114)     \
	F_KEY_REGISTER(115)     \
	F_KEY_REGISTER(116)     \
	F_KEY_REGISTER(117)     \
	F_KEY_REGISTER(118)     \
	F_KEY_REGISTER(119)     \
	F_KEY_REGISTER(120)     \
	F_KEY_REGISTER(121)     \
	F_KEY_REGISTER(122)     \
	F_KEY_REGISTER(123)     \
	F_KEY_REGISTER(124)     \
	F_KEY_REGISTER(125)     \
	F_KEY_REGISTER(126)     \

#endif
